# Generated by Django 5.2.1 on 2025-05-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="Name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="patient",
            name="detail",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], default="name"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medicine_detail",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="mobile",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_visit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="note",
            field=models.TextField(null=True),
        ),
    ]
